#version: '3'
services:
  public-app4-r:
    build: ./
    container_name: public-app4-r
    restart: always
    ports:
     - ${PHP_PORT}:80
    env_file: .env
    volumes:
     - ./:/var/www/html
     - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - sql_default
networks:
  sql_default:
    external: true
    name: sql_default

