version: '3'
services:
  app4:
    build: ./
    container_name: apache-app4
    restart: always
    ports:
     - ${PHP_PORT}:80
    env_file: .env
    volumes:
     - ./home/app4:/var/www/html
     - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - mvc
networks:
  mvc:
    external: true
    name: mvc